export const flags = {
  multiTimeframe: true,
  multiSymbolOverlay: true,
  pineRunner: true,
  orderFlow: true,
  quickOrderPanel: true,
  tradingJournal: true,
  mtfBacktest: true,
  aiPatterns: true,
  aiIndicatorSuggest: true,
  aiMarketSummary: true,
  wasmEnabled: false,
  idbCache: true,
  offscreenRenderer: false,
  draggablePanels: true,
  fullScreenAutoDark: true,
  themesMarketplace: true,
  providersUI: true,
  exportIntegrations: true,
  socialShare: true,
};