/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

export interface LogoInfo {
  path?: string;
  color?: string;
  type: 'company' | 'index' | 'commodity' | 'crypto' | 'forex' | 'token' | 'fallback';
  isIndex?: boolean;
  isCompany?: boolean;
  isCommodity?: boolean;
  isCrypto?: boolean;
  isForex?: boolean;
  isExtra?: boolean;
  fallback_if_missing?: string;
}

// Maps symbol IDs/tickers to their logo information
export const logoMap: Record<string, LogoInfo> = {
  // --- Defaults ---
  "DEFAULT": { "path": "/assets/fallback/generic.svg", "color":"#7A7A7A", "type": "fallback" },

  // --- Indices ---
  "TASI":  { "path": "/assets/exchanges/tadawul.svg",    "color":"#1B4DB1", "type":"index", "isIndex":true },
  "MT30":  { "path": "/assets/exchanges/mt30.svg",       "color":"#1560D9", "type":"index", "isIndex":true },
  "SPX":   { "path": "/assets/exchanges/sp500.svg",      "color":"#1B1F3B", "type":"index", "isIndex":true },
  "NDX":   { "path": "/assets/exchanges/nasdaq100.svg",  "color":"#0072CE", "type":"index", "isIndex":true },
  "DJI":   { "path": "/assets/exchanges/dowjones.svg",   "color":"#0054A6", "type":"index", "isIndex":true },
  "UKX":   { "path": "/assets/exchanges/ftse.svg",       "color":"#0A2740", "type":"index", "isIndex":true },
  "DEU40": { "path": "/assets/exchanges/dax.svg",        "color":"#202020", "type":"index", "isIndex":true },
  "FCHI":  { "path": "/assets/exchanges/cac40.svg",      "color":"#003DA5", "type":"index", "isIndex":true },
  "NI225": { "path": "/assets/exchanges/nikkei.svg",     "color":"#E60012", "type":"index", "isIndex":true },
  "HSI":   { "path": "/assets/exchanges/hsi.svg",        "color":"#DC143C", "type":"index", "isIndex":true },

  // --- Saudi & GCC Companies ---
  "2222": { "path": "/assets/companies/aramco.svg",       "color":"#009A44","type":"company","isCompany":true },
  "7010": { "path": "/assets/companies/stc.svg",          "color":"#3E007D","type":"company","isCompany":true },
  "1180": { "path": "/assets/companies/snb.svg",          "color":"#006C65","type":"company","isCompany":true },
  "1120": { "path": "/assets/companies/alrajhi.svg",      "color":"#0046AD","type":"company","isCompany":true },
  "2010": { "path": "/assets/companies/sabic.svg",        "color":"#FCA311","type":"company","isCompany":true },
  "1211": { "path": "/assets/companies/maaden.svg",       "color":"#006B54","type":"company","isCompany":true },
  "1111": { "path": "/assets/companies/tadawul-group.svg","color":"#102B65","type":"company","isCompany":true },
  "1020": { "path": "/assets/companies/riyad-bank.svg",   "color":"#5A2D82","type":"company","isCompany":true },
  "1150": { "path": "/assets/companies/alinma.svg",       "color":"#006747","type":"company","isCompany":true },
  "1050": { "path": "/assets/companies/fransi.svg",       "color":"#0094D8","type":"company","isCompany":true },
  "1080": { "path": "/assets/companies/anb.svg",          "color":"#006B54","type":"company","isCompany":true },
  "4190": { "path": "/assets/companies/jarir.svg",        "color":"#D71920","type":"company","isCompany":true },
  "4003": { "path": "/assets/companies/extra.svg",        "color":"#0071CE","type":"company","isCompany":true },
  "7020": { "path": "/assets/companies/mobily.svg",       "color":"#009DDC","type":"company","isCompany":true },
  "2380": { "path": "/assets/companies/petrorabigh.svg",  "color":"#00843D","type":"company","isCompany":true },
  "2040": { "path": "/assets/companies/savola.svg",       "color":"#2B6C4D","type":"company","isCompany":true },
  "2082": { "path": "/assets/companies/tasnee.svg",       "color":"#0076A8","type":"company","isCompany":true },
  
  // --- Global Companies ---
  "AAPL": { "path": "/assets/companies/apple.svg",     "color":"#000000","type":"company","isCompany":true },
  "MSFT": { "path": "/assets/companies/microsoft.svg", "color":"#0078D4","type":"company","isCompany":true },
  "NVDA": { "path": "/assets/companies/nvidia.svg",    "color":"#76B900","type":"company","isCompany":true },
  "GOOGL":{ "path": "/assets/companies/google.svg",    "color":"#4285F4","type":"company","isCompany":true },
  "AMZN": { "path": "/assets/companies/amazon.svg",    "color":"#FF9900","type":"company","isCompany":true },
  "META": { "path": "/assets/companies/meta.svg",      "color":"#0866FF","type":"company","isCompany":true },
  "TSLA": { "path": "/assets/companies/tesla.svg",     "color":"#CC0000","type":"company","isCompany":true },
  "JPM":  { "path": "/assets/companies/jpmorgan.svg",  "color":"#2E6E9E","type":"company","isCompany":true },

  // --- Commodities (real pictograms) ---
  "USOIL":  { "path": "/assets/commodities/usoil.svg",       "color": "#2B2B2B", "type": "commodity", "isCommodity": true, "fallback_if_missing": "/assets/commodities/crude-oil.svg" },
  "UKOIL":  { "path": "/assets/commodities/ukoil.svg",       "color": "#2D2D2D", "type": "commodity", "isCommodity": true, "fallback_if_missing": "/assets/commodities/crude-oil.svg" },
  "!CL1": { "path": "/assets/commodities/crude-oil.svg",   "color": "#1E1E1E", "type": "commodity", "isCommodity": true },
  "NATGAS": { "path": "/assets/commodities/natural-gas.svg", "color": "#00A2FF", "type": "commodity", "isCommodity": true },
  "!NG1": { "path": "/assets/commodities/natural-gas.svg", "color": "#00A2FF", "type": "commodity", "isCommodity": true },
  "GOLD":   { "path": "/assets/commodities/gold.svg",        "color": "#FFD700", "type": "commodity", "isCommodity": true },
  "!GC1": { "path": "/assets/commodities/gold.svg",        "color": "#FFD700", "type": "commodity", "isCommodity": true },
  "SILVER": { "path": "/assets/commodities/silver.svg",      "color": "#C0C0C0", "type": "commodity", "isCommodity": true },
  "!SI1": { "path": "/assets/commodities/silver.svg",      "color": "#C0C0C0", "type": "commodity", "isCommodity": true },
  "COPPER": { "path": "/assets/commodities/copper.svg",      "color": "#B87333", "type": "commodity", "isCommodity": true },
  "!HG1": { "path": "/assets/commodities/copper.svg",      "color": "#B87333", "type": "commodity", "isCommodity": true },
  "PLATINUM": { "path": "/assets/commodities/platinum.svg",  "color": "#A8A8A8", "type": "commodity", "isCommodity": true },
  "PALLADIUM":{ "path": "/assets/commodities/palladium.svg", "color": "#E0E0E0", "type": "commodity", "isCommodity": true },
  "ALUMINIUM":{ "path": "/assets/commodities/aluminium.svg", "color": "#C8C8C8", "type": "commodity", "isCommodity": true },
  "NICKEL":   { "path": "/assets/commodities/nickel.svg",    "color": "#7E7E7E", "type": "commodity", "isCommodity": true },
  "ZINC":     { "path": "/assets/commodities/zinc.svg",      "color": "#7A7A7A", "type": "commodity", "isCommodity": true },
  "IRON":     { "path": "/assets/commodities/iron.svg",      "color": "#787878", "type": "commodity", "isCommodity": true },
  "LITHIUM":  { "path": "/assets/commodities/lithium.svg",   "color": "#8BD3DD", "type": "commodity", "isCommodity": true },
  "URANIUM":  { "path": "/assets/commodities/uranium.svg",   "color": "#5FA857", "type": "commodity", "isCommodity": true },
  "CORN":     { "path": "/assets/commodities/corn.svg",      "color": "#D4AF37", "type": "commodity", "isCommodity": true },
  "WHEAT":    { "path": "/assets/commodities/wheat.svg",     "color": "#D1A054", "type": "commodity", "isCommodity": true },
  "SOYBEAN":  { "path": "/assets/commodities/soybean.svg",   "color": "#9E8650", "type": "commodity", "isCommodity": true },
  "COFFEE":   { "path": "/assets/commodities/coffee.svg",    "color": "#6F4E37", "type": "commodity", "isCommodity": true },
  "COCOA":    { "path": "/assets/commodities/cocoa.svg",     "color": "#4B2E05", "type": "commodity", "isCommodity": true },
  "SUGAR":    { "path": "/assets/commodities/sugar.svg",     "color": "#E5E5E5", "type": "commodity", "isCommodity": true },
  "COTTON":   { "path": "/assets/commodities/cotton.svg",    "color": "#B0C4DE", "type": "commodity", "isCommodity": true },
  "ORANGE":   { "path": "/assets/commodities/orange-juice.svg", "color": "#FFA500", "type": "commodity", "isCommodity": true },
  "RICE":     { "path": "/assets/commodities/rice.svg",      "color": "#EAD8B1", "type": "commodity", "isCommodity": true },
  "PALMOIL":  { "path": "/assets/commodities/palmoil.svg",   "color": "#CC7722", "type": "commodity", "isCommodity": true },
  "WOOD":     { "path": "/assets/commodities/lumber.svg",    "color": "#8B5A2B", "type": "commodity", "isCommodity": true },
  "COAL":     { "path": "/assets/commodities/coal.svg",      "color": "#3B3B3B", "type": "commodity", "isCommodity": true },
  "GASOLINE": { "path": "/assets/commodities/gasoline.svg",  "color": "#CC3300", "type": "commodity", "isCommodity": true },
  "DIESEL":   { "path": "/assets/commodities/diesel.svg",    "color": "#4F4F4F", "type": "commodity", "isCommodity": true },

  // --- Forex Flags ---
  "EURUSD": { "path": "/assets/flags/eu.png","type":"forex","isForex":true },
  "USDJPY": { "path": "/assets/flags/jp.png","type":"forex","isForex":true },
  "GBPUSD": { "path": "/assets/flags/gb.png","type":"forex","isForex":true },
  "USDSAR": { "path": "/assets/flags/sa.png","type":"forex","isForex":true },
  "USDCAD": { "path": "/assets/flags/ca.png","type":"forex","isForex":true },
  "AUDUSD": { "path": "/assets/flags/au.png","type":"forex","isForex":true },
  "USDCHF": { "path": "/assets/flags/ch.png","type":"forex","isForex":true },

  // --- Cryptocurrencies (base + seeded) ---
  "BTC":   { "path": "/assets/icons/crypto/BTC.svg",   "color":"#F7931A","type":"crypto","isCrypto":true,"isIndex":false },
  "BTCUSD": { "path": "/assets/icons/crypto/BTC.svg",   "color":"#F7931A","type":"crypto","isCrypto":true,"isIndex":false },
  "BTCUSDT": { "path": "/assets/icons/crypto/BTC.svg",   "color":"#F7931A","type":"crypto","isCrypto":true,"isIndex":false },
  "ETH":   { "path": "/assets/icons/crypto/ETH.svg",   "color":"#3C3C3D","type":"crypto","isCrypto":true,"isIndex":false },
  "ETHUSD": { "path": "/assets/icons/crypto/ETH.svg",   "color":"#3C3C3D","type":"crypto","isCrypto":true,"isIndex":false },
  "ETHUSDT": { "path": "/assets/icons/crypto/ETH.svg",   "color":"#3C3C3D","type":"crypto","isCrypto":true,"isIndex":false },
  "BNB":   { "path": "/assets/icons/crypto/BNB.svg",   "color":"#F3BA2F","type":"crypto","isCrypto":true,"isIndex":false },
  "BNBUSD": { "path": "/assets/icons/crypto/BNB.svg",   "color":"#F3BA2F","type":"crypto","isCrypto":true,"isIndex":false },
  "BNBUSDT": { "path": "/assets/icons/crypto/BNB.svg",   "color":"#F3BA2F","type":"crypto","isCrypto":true,"isIndex":false },
  "XRP":   { "path": "/assets/icons/crypto/XRP.svg",   "color":"#23292F","type":"crypto","isCrypto":true,"isIndex":false },
  "XRPUSD": { "path": "/assets/icons/crypto/XRP.svg",   "color":"#23292F","type":"crypto","isCrypto":true,"isIndex":false },
  "XRPUSDT": { "path": "/assets/icons/crypto/XRP.svg",   "color":"#23292F","type":"crypto","isCrypto":true,"isIndex":false },
  "ADA":   { "path": "/assets/icons/crypto/ADA.svg",   "color":"#0033AD","type":"crypto","isCrypto":true,"isIndex":false },
  "ADAUSD": { "path": "/assets/icons/crypto/ADA.svg",   "color":"#0033AD","type":"crypto","isCrypto":true,"isIndex":false },
  "ADAUSDT": { "path": "/assets/icons/crypto/ADA.svg",   "color":"#0033AD","type":"crypto","isCrypto":true,"isIndex":false },
  "DOGE":  { "path": "/assets/icons/crypto/DOGE.svg",  "color":"#C2A633","type":"crypto","isCrypto":true,"isIndex":false },
  "DOGEUSD": { "path": "/assets/icons/crypto/DOGE.svg",  "color":"#C2A633","type":"crypto","isCrypto":true,"isIndex":false },
  "DOGEUSDT": { "path": "/assets/icons/crypto/DOGE.svg",  "color":"#C2A633","type":"crypto","isCrypto":true,"isIndex":false },
  "SOL":   { "path": "/assets/icons/crypto/SOL.svg",   "color":"#14F195","type":"crypto","isCrypto":true,"isIndex":false },
  "SOLUSD": { "path": "/assets/icons/crypto/SOL.svg",   "color":"#14F195","type":"crypto","isCrypto":true,"isIndex":false },
  "SOLUSDT": { "path": "/assets/icons/crypto/SOL.svg",   "color":"#14F195","type":"crypto","isCrypto":true,"isIndex":false },
  "TON":   { "path": "/assets/icons/crypto/TON.svg",   "color":"#0098EA","type":"crypto","isCrypto":true,"isIndex":false },
  "TONUSD": { "path": "/assets/icons/crypto/TON.svg",   "color":"#0098EA","type":"crypto","isCrypto":true,"isIndex":false },
  "TONUSDT": { "path": "/assets/icons/crypto/TON.svg",   "color":"#0098EA","type":"crypto","isCrypto":true,"isIndex":false },
  "TRX":   { "path": "/assets/icons/crypto/TRX.svg",   "color":"#EF0027","type":"crypto","isCrypto":true,"isIndex":false },
  "TRXUSD": { "path": "/assets/icons/crypto/TRX.svg",   "color":"#EF0027","type":"crypto","isCrypto":true,"isIndex":false },
  "TRXUSDT": { "path": "/assets/icons/crypto/TRX.svg",   "color":"#EF0027","type":"crypto","isCrypto":true,"isIndex":false },
  "DOT":   { "path": "/assets/icons/crypto/DOT.svg",   "color":"#E6007A","type":"crypto","isCrypto":true,"isIndex":false },
  "DOTUSD": { "path": "/assets/icons/crypto/DOT.svg",   "color":"#E6007A","type":"crypto","isCrypto":true,"isIndex":false },
  "DOTUSDT": { "path": "/assets/icons/crypto/DOT.svg",   "color":"#E6007A","type":"crypto","isCrypto":true,"isIndex":false },
  "MATIC": { "path": "/assets/icons/crypto/MATIC.svg", "color":"#8247E5","type":"crypto","isCrypto":true,"isIndex":false },
  "MATICUSD": { "path": "/assets/icons/crypto/MATIC.svg", "color":"#8247E5","type":"crypto","isCrypto":true,"isIndex":false },
  "MATICUSDT": { "path": "/assets/icons/crypto/MATIC.svg", "color":"#8247E5","type":"crypto","isCrypto":true,"isIndex":false },
  "LTC":   { "path": "/assets/icons/crypto/LTC.svg",   "color":"#345C9C","type":"crypto","isCrypto":true,"isIndex":false },
  "LTCUSD": { "path": "/assets/icons/crypto/LTC.svg",   "color":"#345C9C","type":"crypto","isCrypto":true,"isIndex":false },
  "LTCUSDT": { "path": "/assets/icons/crypto/LTC.svg",   "color":"#345C9C","type":"crypto","isCrypto":true,"isIndex":false },
  "BCH": { "path": "/assets/icons/crypto/BCH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BCHUSD": { "path": "/assets/icons/crypto/BCH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BCHUSDT": { "path": "/assets/icons/crypto/BCH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AVAX":  { "path": "/assets/icons/crypto/AVAX.svg",  "color":"#E84142","type":"crypto","isCrypto":true,"isIndex":false },
  "AVAXUSD": { "path": "/assets/icons/crypto/AVAX.svg",  "color":"#E84142","type":"crypto","isCrypto":true,"isIndex":false },
  "AVAXUSDT": { "path": "/assets/icons/crypto/AVAX.svg",  "color":"#E84142","type":"crypto","isCrypto":true,"isIndex":false },
  "LINK":  { "path": "/assets/icons/crypto/LINK.svg",  "color":"#295ADA","type":"crypto","isCrypto":true,"isIndex":false },
  "LINKUSD": { "path": "/assets/icons/crypto/LINK.svg",  "color":"#295ADA","type":"crypto","isCrypto":true,"isIndex":false },
  "LINKUSDT": { "path": "/assets/icons/crypto/LINK.svg",  "color":"#295ADA","type":"crypto","isCrypto":true,"isIndex":false },
  "XLM": { "path": "/assets/icons/crypto/XLM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "XLMUSD": { "path": "/assets/icons/crypto/XLM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "XLMUSDT": { "path": "/assets/icons/crypto/XLM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "XMR": { "path": "/assets/icons/crypto/XMR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "XMRUSD": { "path": "/assets/icons/crypto/XMR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "XMRUSDT": { "path": "/assets/icons/crypto/XMR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ETC": { "path": "/assets/icons/crypto/ETC.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ETCUSD": { "path": "/assets/icons/crypto/ETC.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ETCUSDT": { "path": "/assets/icons/crypto/ETC.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ATOM":  { "path": "/assets/icons/crypto/ATOM.svg",  "color":"#6F6F6F","type":"crypto","isCrypto":true,"isIndex":false },
  "ATOMUSD": { "path": "/assets/icons/crypto/ATOM.svg",  "color":"#6F6F6F","type":"crypto","isCrypto":true,"isIndex":false },
  "ATOMUSDT": { "path": "/assets/icons/crypto/ATOM.svg",  "color":"#6F6F6F","type":"crypto","isCrypto":true,"isIndex":false },
  "ALGO": { "path": "/assets/icons/crypto/ALGO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ALGOUSD": { "path": "/assets/icons/crypto/ALGO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ALGOUSDT": { "path": "/assets/icons/crypto/ALGO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "VET": { "path": "/assets/icons/crypto/VET.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "VETUSD": { "path": "/assets/icons/crypto/VET.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "VETUSDT": { "path": "/assets/icons/crypto/VET.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FIL": { "path": "/assets/icons/crypto/FIL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FILUSD": { "path": "/assets/icons/crypto/FIL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FILUSDT": { "path": "/assets/icons/crypto/FIL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ICP": { "path": "/assets/icons/crypto/ICP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ICPUSD": { "path": "/assets/icons/crypto/ICP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ICPUSDT": { "path": "/assets/icons/crypto/ICP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "APT": { "path": "/assets/icons/crypto/APT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "APTUSD": { "path": "/assets/icons/crypto/APT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "APTUSDT": { "path": "/assets/icons/crypto/APT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ARB": { "path": "/assets/icons/crypto/ARB.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ARBUSD": { "path": "/assets/icons/crypto/ARB.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ARBUSDT": { "path": "/assets/icons/crypto/ARB.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "OP": { "path": "/assets/icons/crypto/OP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "OPUSD": { "path": "/assets/icons/crypto/OP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "OPUSDT": { "path": "/assets/icons/crypto/OP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SUI": { "path": "/assets/icons/crypto/SUI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SUIUSD": { "path": "/assets/icons/crypto/SUI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SUIUSDT": { "path": "/assets/icons/crypto/SUI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SHIB": { "path": "/assets/icons/crypto/SHIB.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SHIBUSD": { "path": "/assets/icons/crypto/SHIB.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SHIBUSDT": { "path": "/assets/icons/crypto/SHIB.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PEPE": { "path": "/assets/icons/crypto/PEPE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PEPEUSD": { "path": "/assets/icons/crypto/PEPE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PEPEUSDT": { "path": "/assets/icons/crypto/PEPE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FLOKI": { "path": "/assets/icons/crypto/FLOKI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FLOKIUSD": { "path": "/assets/icons/crypto/FLOKI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FLOKIUSDT": { "path": "/assets/icons/crypto/FLOKI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "INJ": { "path": "/assets/icons/crypto/INJ.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "INJUSD": { "path": "/assets/icons/crypto/INJ.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "INJUSDT": { "path": "/assets/icons/crypto/INJ.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GRT": { "path": "/assets/icons/crypto/GRT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GRTUSD": { "path": "/assets/icons/crypto/GRT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GRTUSDT": { "path": "/assets/icons/crypto/GRT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AAVE":  { "path": "/assets/icons/crypto/AAVE.svg",  "color":"#B6509E","type":"crypto","isCrypto":true,"isIndex":false },
  "AAVEUSD": { "path": "/assets/icons/crypto/AAVE.svg",  "color":"#B6509E","type":"crypto","isCrypto":true,"isIndex":false },
  "AAVEUSDT": { "path": "/assets/icons/crypto/AAVE.svg",  "color":"#B6509E","type":"crypto","isCrypto":true,"isIndex":false },
  "MKR": { "path": "/assets/icons/crypto/MKR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MKRUSD": { "path": "/assets/icons/crypto/MKR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MKRUSDT": { "path": "/assets/icons/crypto/MKR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "COMP": { "path": "/assets/icons/crypto/COMP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "COMPUSD": { "path": "/assets/icons/crypto/COMP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "COMPUSDT": { "path": "/assets/icons/crypto/COMP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SNX": { "path": "/assets/icons/crypto/SNX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SNXUSD": { "path": "/assets/icons/crypto/SNX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SNXUSDT": { "path": "/assets/icons/crypto/SNX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "LDO": { "path": "/assets/icons/crypto/LDO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "LDOUSD": { "path": "/assets/icons/crypto/LDO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "LDOUSDT": { "path": "/assets/icons/crypto/LDO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RPL": { "path": "/assets/icons/crypto/RPL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RPLUSD": { "path": "/assets/icons/crypto/RPL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RPLUSDT": { "path": "/assets/icons/crypto/RPL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "STX": { "path": "/assets/icons/crypto/STX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "STXUSD": { "path": "/assets/icons/crypto/STX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "STXUSDT": { "path": "/assets/icons/crypto/STX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NEAR": { "path": "/assets/icons/crypto/NEAR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NEARUSD": { "path": "/assets/icons/crypto/NEAR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NEARUSDT": { "path": "/assets/icons/crypto/NEAR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "HBAR": { "path": "/assets/icons/crypto/HBAR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "HBARUSD": { "path": "/assets/icons/crypto/HBAR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "HBARUSDT": { "path": "/assets/icons/crypto/HBAR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "EGLD": { "path": "/assets/icons/crypto/EGLD.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "EGLDUSD": { "path": "/assets/icons/crypto/EGLD.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "EGLDUSDT": { "path": "/assets/icons/crypto/EGLD.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KAS": { "path": "/assets/icons/crypto/KAS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KASUSD": { "path": "/assets/icons/crypto/KAS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KASUSDT": { "path": "/assets/icons/crypto/KAS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KAVA": { "path": "/assets/icons/crypto/KAVA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KAVAUSD": { "path": "/assets/icons/crypto/KAVA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KAVAUSDT": { "path": "/assets/icons/crypto/KAVA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CAKE": { "path": "/assets/icons/crypto/CAKE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CAKEUSD": { "path": "/assets/icons/crypto/CAKE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CAKEUSDT": { "path": "/assets/icons/crypto/CAKE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GMX": { "path": "/assets/icons/crypto/GMX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GMXUSD": { "path": "/assets/icons/crypto/GMX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GMXUSDT": { "path": "/assets/icons/crypto/GMX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DYDX": { "path": "/assets/icons/crypto/DYDX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DYDXUSD": { "path": "/assets/icons/crypto/DYDX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DYDXUSDT": { "path": "/assets/icons/crypto/DYDX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RUNE": { "path": "/assets/icons/crypto/RUNE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RUNEUSD": { "path": "/assets/icons/crypto/RUNE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RUNEUSDT": { "path": "/assets/icons/crypto/RUNE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "THETA": { "path": "/assets/icons/crypto/THETA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "THETAUSD": { "path": "/assets/icons/crypto/THETA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "THETAUSDT": { "path": "/assets/icons/crypto/THETA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MANA": { "path": "/assets/icons/crypto/MANA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MANAUSD": { "path": "/assets/icons/crypto/MANA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MANAUSDT": { "path": "/assets/icons/crypto/MANA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SAND": { "path": "/assets/icons/crypto/SAND.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SANDUSD": { "path": "/assets/icons/crypto/SAND.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SANDUSDT": { "path": "/assets/icons/crypto/SAND.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ENJ": { "path": "/assets/icons/crypto/ENJ.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ENJUSD": { "path": "/assets/icons/crypto/ENJ.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ENJUSDT": { "path": "/assets/icons/crypto/ENJ.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CHZ": { "path": "/assets/icons/crypto/CHZ.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CHZUSD": { "path": "/assets/icons/crypto/CHZ.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CHZUSDT": { "path": "/assets/icons/crypto/CHZ.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CRV": { "path": "/assets/icons/crypto/CRV.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CRVUSD": { "path": "/assets/icons/crypto/CRV.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CRVUSDT": { "path": "/assets/icons/crypto/CRV.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CVX": { "path": "/assets/icons/crypto/CVX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CVXUSD": { "path": "/assets/icons/crypto/CVX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CVXUSDT": { "path": "/assets/icons/crypto/CVX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "1INCH": { "path": "/assets/icons/crypto/1INCH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "1INCHUSD": { "path": "/assets/icons/crypto/1INCH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "1INCHUSDT": { "path": "/assets/icons/crypto/1INCH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BAL": { "path": "/assets/icons/crypto/BAL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BALUSD": { "path": "/assets/icons/crypto/BAL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BALUSDT": { "path": "/assets/icons/crypto/BAL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ZRX": { "path": "/assets/icons/crypto/ZRX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ZRXUSD": { "path": "/assets/icons/crypto/ZRX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ZRXUSDT": { "path": "/assets/icons/crypto/ZRX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "UMA": { "path": "/assets/icons/crypto/UMA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "UMAUSD": { "path": "/assets/icons/crypto/UMA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "UMAUSDT": { "path": "/assets/icons/crypto/UMA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "YFI": { "path": "/assets/icons/crypto/YFI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "YFIUSD": { "path": "/assets/icons/crypto/YFI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "YFIUSDT": { "path": "/assets/icons/crypto/YFI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "REN": { "path": "/assets/icons/crypto/REN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RENUSD": { "path": "/assets/icons/crypto/REN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RENUSDT": { "path": "/assets/icons/crypto/REN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BAND": { "path": "/assets/icons/crypto/BAND.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BANDUSD": { "path": "/assets/icons/crypto/BAND.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BANDUSDT": { "path": "/assets/icons/crypto/BAND.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "OCEAN": { "path": "/assets/icons/crypto/OCEAN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "OCEANUSD": { "path": "/assets/icons/crypto/OCEAN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "OCEANUSDT": { "path": "/assets/icons/crypto/OCEAN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FET": { "path": "/assets/icons/crypto/FET.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FETUSD": { "path": "/assets/icons/crypto/FET.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FETUSDT": { "path": "/assets/icons/crypto/FET.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GALA": { "path": "/assets/icons/crypto/GALA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GALAUSD": { "path": "/assets/icons/crypto/GALA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GALAUSDT": { "path": "/assets/icons/crypto/GALA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "IMX": { "path": "/assets/icons/crypto/IMX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "IMXUSD": { "path": "/assets/icons/crypto/IMX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "IMXUSDT": { "path": "/assets/icons/crypto/IMX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AXS": { "path": "/assets/icons/crypto/AXS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AXSUSD": { "path": "/assets/icons/crypto/AXS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AXSUSDT": { "path": "/assets/icons/crypto/AXS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SUSHI": { "path": "/assets/icons/crypto/SUSHI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SUSHIUSD": { "path": "/assets/icons/crypto/SUSHI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SUSHIUSDT": { "path": "/assets/icons/crypto/SUSHI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RSR": { "path": "/assets/icons/crypto/RSR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RSRUSD": { "path": "/assets/icons/crypto/RSR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RSRUSDT": { "path": "/assets/icons/crypto/RSR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CELR": { "path": "/assets/icons/crypto/CELR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CELRUSD": { "path": "/assets/icons/crypto/CELR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CELRUSDT": { "path": "/assets/icons/crypto/CELR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "HOT": { "path": "/assets/icons/crypto/HOT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "HOTUSD": { "path": "/assets/icons/crypto/HOT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "HOTUSDT": { "path": "/assets/icons/crypto/HOT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NEO": { "path": "/assets/icons/crypto/NEO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NEOUSD": { "path": "/assets/icons/crypto/NEO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NEOUSDT": { "path": "/assets/icons/crypto/NEO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ONT": { "path": "/assets/icons/crypto/ONT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ONTUSD": { "path": "/assets/icons/crypto/ONT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ONTUSDT": { "path": "/assets/icons/crypto/ONT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "WAVES": { "path": "/assets/icons/crypto/WAVES.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "WAVESUSD": { "path": "/assets/icons/crypto/WAVES.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "WAVESUSDT": { "path": "/assets/icons/crypto/WAVES.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ZIL": { "path": "/assets/icons/crypto/ZIL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ZILUSD": { "path": "/assets/icons/crypto/ZIL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ZILUSDT": { "path": "/assets/icons/crypto/ZIL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "QTUM": { "path": "/assets/icons/crypto/QTUM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "QTUMUSD": { "path": "/assets/icons/crypto/QTUM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "QTUMUSDT": { "path": "/assets/icons/crypto/QTUM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ICX": { "path": "/assets/icons/crypto/ICX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ICXUSD": { "path": "/assets/icons/crypto/ICX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ICXUSDT": { "path": "/assets/icons/crypto/ICX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KSM": { "path": "/assets/icons/crypto/KSM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KSMUSD": { "path": "/assets/icons/crypto/KSM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KSMUSDT": { "path": "/assets/icons/crypto/KSM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ROSE": { "path": "/assets/icons/crypto/ROSE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ROSEUSD": { "path": "/assets/icons/crypto/ROSE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ROSEUSDT": { "path": "/assets/icons/crypto/ROSE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AR": { "path": "/assets/icons/crypto/AR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ARUSD": { "path": "/assets/icons/crypto/AR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ARUSDT": { "path": "/assets/icons/crypto/AR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KDA": { "path": "/assets/icons/crypto/KDA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KDAUSD": { "path": "/assets/icons/crypto/KDA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KDAUSDT": { "path": "/assets/icons/crypto/KDA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CSPR": { "path": "/assets/icons/crypto/CSPR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CSPRUSD": { "path": "/assets/icons/crypto/CSPR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CSPRUSDT": { "path": "/assets/icons/crypto/CSPR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MINA": { "path": "/assets/icons/crypto/MINA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MINAUSD": { "path": "/assets/icons/crypto/MINA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MINAUSDT": { "path": "/assets/icons/crypto/MINA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KLAY": { "path": "/assets/icons/crypto/KLAY.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KLAYUSD": { "path": "/assets/icons/crypto/KLAY.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KLAYUSDT": { "path": "/assets/icons/crypto/KLAY.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SCRT": { "path": "/assets/icons/crypto/SCRT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SCRTUSD": { "path": "/assets/icons/crypto/SCRT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SCRTUSDT": { "path": "/assets/icons/crypto/SCRT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CELO": { "path": "/assets/icons/crypto/CELO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CELOUSD": { "path": "/assets/icons/crypto/CELO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CELOUSDT": { "path": "/assets/icons/crypto/CELO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GNO": { "path": "/assets/icons/crypto/GNO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GNOUSD": { "path": "/assets/icons/crypto/GNO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GNOUSDT": { "path": "/assets/icons/crypto/GNO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ENS": { "path": "/assets/icons/crypto/ENS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ENSUSD": { "path": "/assets/icons/crypto/ENS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ENSUSDT": { "path": "/assets/icons/crypto/ENS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GLMR": { "path": "/assets/icons/crypto/GLMR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GLMRUSD": { "path": "/assets/icons/crypto/GLMR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GLMRUSDT": { "path": "/assets/icons/crypto/GLMR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ASTR": { "path": "/assets/icons/crypto/ASTR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ASTRUSD": { "path": "/assets/icons/crypto/ASTR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ASTRUSDT": { "path": "/assets/icons/crypto/ASTR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FXS": { "path": "/assets/icons/crypto/FXS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FXSUSD": { "path": "/assets/icons/crypto/FXS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FXSUSDT": { "path": "/assets/icons/crypto/FXS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "LRC": { "path": "/assets/icons/crypto/LRC.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "LRCUSD": { "path": "/assets/icons/crypto/LRC.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "LRCUSDT": { "path": "/assets/icons/crypto/LRC.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MASK": { "path": "/assets/icons/crypto/MASK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MASKUSD": { "path": "/assets/icons/crypto/MASK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MASKUSDT": { "path": "/assets/icons/crypto/MASK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ILV": { "path": "/assets/icons/crypto/ILV.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ILVUSD": { "path": "/assets/icons/crypto/ILV.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ILVUSDT": { "path": "/assets/icons/crypto/ILV.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "HNT": { "path": "/assets/icons/crypto/HNT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "HNTUSD": { "path": "/assets/icons/crypto/HNT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "HNTUSDT": { "path": "/assets/icons/crypto/HNT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ANKR": { "path": "/assets/icons/crypto/ANKR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ANKRUSD": { "path": "/assets/icons/crypto/ANKR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ANKRUSDT": { "path": "/assets/icons/crypto/ANKR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AMP": { "path": "/assets/icons/crypto/AMP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AMPUSD": { "path": "/assets/icons/crypto/AMP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AMPUSDT": { "path": "/assets/icons/crypto/AMP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "STG": { "path": "/assets/icons/crypto/STG.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "STGUSD": { "path": "/assets/icons/crypto/STG.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "STGUSDT": { "path": "/assets/icons/crypto/STG.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FLR": { "path": "/assets/icons/crypto/FLR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FLRUSD": { "path": "/assets/icons/crypto/FLR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FLRUSDT": { "path": "/assets/icons/crypto/FLR.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SFP": { "path": "/assets/icons/crypto/SFP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SFPUSD": { "path": "/assets/icons/crypto/SFP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SFPUSDT": { "path": "/assets/icons/crypto/SFP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BNT": { "path": "/assets/icons/crypto/BNT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BNTUSD": { "path": "/assets/icons/crypto/BNT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BNTUSDT": { "path": "/assets/icons/crypto/BNT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RLC": { "path": "/assets/icons/crypto/RLC.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RLCUSD": { "path": "/assets/icons/crypto/RLC.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RLCUSDT": { "path": "/assets/icons/crypto/RLC.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "API3": { "path": "/assets/icons/crypto/API3.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "API3USD": { "path": "/assets/icons/crypto/API3.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "API3USDT": { "path": "/assets/icons/crypto/API3.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ALPHA": { "path": "/assets/icons/crypto/ALPHA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ALPHAUSD": { "path": "/assets/icons/crypto/ALPHA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ALPHAUSDT": { "path": "/assets/icons/crypto/ALPHA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DASH": { "path": "/assets/icons/crypto/DASH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DASHUSD": { "path": "/assets/icons/crypto/DASH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DASHUSDT": { "path": "/assets/icons/crypto/DASH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TWT": { "path": "/assets/icons/crypto/TWT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TWTUSD": { "path": "/assets/icons/crypto/TWT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TWTUSDT": { "path": "/assets/icons/crypto/TWT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TRB": { "path": "/assets/icons/crypto/TRB.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TRBUSD": { "path": "/assets/icons/crypto/TRB.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TRBUSDT": { "path": "/assets/icons/crypto/TRB.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JOE": { "path": "/assets/icons/crypto/JOE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JOEUSD": { "path": "/assets/icons/crypto/JOE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JOEUSDT": { "path": "/assets/icons/crypto/JOE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GAL": { "path": "/assets/icons/crypto/GAL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GALUSD": { "path": "/assets/icons/crypto/GAL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GALUSDT": { "path": "/assets/icons/crypto/GAL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SSV": { "path": "/assets/icons/crypto/SSV.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SSVUSD": { "path": "/assets/icons/crypto/SSV.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SSVUSDT": { "path": "/assets/icons/crypto/SSV.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KNC": { "path": "/assets/icons/crypto/KNC.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KNCUSD": { "path": "/assets/icons/crypto/KNC.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "KNCUSDT": { "path": "/assets/icons/crypto/KNC.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JST": { "path": "/assets/icons/crypto/JST.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JSTUSD": { "path": "/assets/icons/crypto/JST.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JSTUSDT": { "path": "/assets/icons/crypto/JST.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "OMG": { "path": "/assets/icons/crypto/OMG.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "OMGUSD": { "path": "/assets/icons/crypto/OMG.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "OMGUSDT": { "path": "/assets/icons/crypto/OMG.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PENDLE": { "path": "/assets/icons/crypto/PENDLE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PENDLEUSD": { "path": "/assets/icons/crypto/PENDLE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PENDLEUSDT": { "path": "/assets/icons/crypto/PENDLE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BADGER": { "path": "/assets/icons/crypto/BADGER.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BADGERUSD": { "path": "/assets/icons/crypto/BADGER.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BADGERUSDT": { "path": "/assets/icons/crypto/BADGER.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RBN": { "path": "/assets/icons/crypto/RBN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RBNUSD": { "path": "/assets/icons/crypto/RBN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "RBNUSDT": { "path": "/assets/icons/crypto/RBN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TOMO": { "path": "/assets/icons/crypto/TOMO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TOMOUSD": { "path": "/assets/icons/crypto/TOMO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TOMOUSDT": { "path": "/assets/icons/crypto/TOMO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GLM": { "path": "/assets/icons/crypto/GLM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GLMUSD": { "path": "/assets/icons/crypto/GLM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "GLMUSDT": { "path": "/assets/icons/crypto/GLM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "WOO": { "path": "/assets/icons/crypto/WOO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "WOOUSD": { "path": "/assets/icons/crypto/WOO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "WOOUSDT": { "path": "/assets/icons/crypto/WOO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FTM": { "path": "/assets/icons/crypto/FTM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FTMUSD": { "path": "/assets/icons/crypto/FTM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "FTMUSDT": { "path": "/assets/icons/crypto/FTM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CFX": { "path": "/assets/icons/crypto/CFX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CFXUSD": { "path": "/assets/icons/crypto/CFX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CFXUSDT": { "path": "/assets/icons/crypto/CFX.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SEI": { "path": "/assets/icons/crypto/SEI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SEIUSD": { "path": "/assets/icons/crypto/SEI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SEIUSDT": { "path": "/assets/icons/crypto/SEI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PYTH": { "path": "/assets/icons/crypto/PYTH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PYTHUSD": { "path": "/assets/icons/crypto/PYTH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PYTHUSDT": { "path": "/assets/icons/crypto/PYTH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JUP": { "path": "/assets/icons/crypto/JUP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JUPUSD": { "path": "/assets/icons/crypto/JUP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JUPUSDT": { "path": "/assets/icons/crypto/JUP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TIA": { "path": "/assets/icons/crypto/TIA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TIAUSD": { "path": "/assets/icons/crypto/TIA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TIAUSDT": { "path": "/assets/icons/crypto/TIA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SAGA": { "path": "/assets/icons/crypto/SAGA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SAGAUSD": { "path": "/assets/icons/crypto/SAGA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SAGAUSDT": { "path": "/assets/icons/crypto/SAGA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TAO": { "path": "/assets/icons/crypto/TAO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TAOUSD": { "path": "/assets/icons/crypto/TAO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TAOUSDT": { "path": "/assets/icons/crypto/TAO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ENA": { "path": "/assets/icons/crypto/ENA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ENAUSD": { "path": "/assets/icons/crypto/ENA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ENAUSDT": { "path": "/assets/icons/crypto/ENA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AEVO": { "path": "/assets/icons/crypto/AEVO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AEVOUSD": { "path": "/assets/icons/crypto/AEVO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AEVOUSDT": { "path": "/assets/icons/crypto/AEVO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JTO": { "path": "/assets/icons/crypto/JTO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JTOUSD": { "path": "/assets/icons/crypto/JTO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JTOUSDT": { "path": "/assets/icons/crypto/JTO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  // FIX: Removed duplicate "W" key from the object literal.
  "WUSD": { "path": "/assets/icons/crypto/W.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "WUSDT": { "path": "/assets/icons/crypto/W.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JASMY": { "path": "/assets/icons/crypto/JASMY.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JASMYUSD": { "path": "/assets/icons/crypto/JASMY.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "JASMYUSDT": { "path": "/assets/icons/crypto/JASMY.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ORDI": { "path": "/assets/icons/crypto/ORDI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ORDIUSD": { "path": "/assets/icons/crypto/ORDI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ORDIUSDT": { "path": "/assets/icons/crypto/ORDI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SATS": { "path": "/assets/icons/crypto/SATS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SATSUSD": { "path": "/assets/icons/crypto/SATS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SATSUSDT": { "path": "/assets/icons/crypto/SATS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NFP": { "path": "/assets/icons/crypto/NFP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NFPUSD": { "path": "/assets/icons/crypto/NFP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NFPUSDT": { "path": "/assets/icons/crypto/NFP.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DEGEN": { "path": "/assets/icons/crypto/DEGEN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DEGENUSD": { "path": "/assets/icons/crypto/DEGEN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DEGENUSDT": { "path": "/assets/icons/crypto/DEGEN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BOME": { "path": "/assets/icons/crypto/BOME.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BOMEUSD": { "path": "/assets/icons/crypto/BOME.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BOMEUSDT": { "path": "/assets/icons/crypto/BOME.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ZK": { "path": "/assets/icons/crypto/ZK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ZKUSD": { "path": "/assets/icons/crypto/ZK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ZKUSDT": { "path": "/assets/icons/crypto/ZK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ZRO": { "path": "/assets/icons/crypto/ZRO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ZROUSD": { "path": "/assets/icons/crypto/ZRO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ZROUSDT": { "path": "/assets/icons/crypto/ZRO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ALT": { "path": "/assets/icons/crypto/ALT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ALTUSD": { "path": "/assets/icons/crypto/ALT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ALTUSDT": { "path": "/assets/icons/crypto/ALT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "XAI": { "path": "/assets/icons/crypto/XAI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "XAIUSD": { "path": "/assets/icons/crypto/XAI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "XAIUSDT": { "path": "/assets/icons/crypto/XAI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "STRK": { "path": "/assets/icons/crypto/STRK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "STRKUSD": { "path": "/assets/icons/crypto/STRK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "STRKUSDT": { "path": "/assets/icons/crypto/STRK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "METIS": { "path": "/assets/icons/crypto/METIS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "METISUSD": { "path": "/assets/icons/crypto/METIS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "METISUSDT": { "path": "/assets/icons/crypto/METIS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BEAM": { "path": "/assets/icons/crypto/BEAM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BEAMUSD": { "path": "/assets/icons/crypto/BEAM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BEAMUSDT": { "path": "/assets/icons/crypto/BEAM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CORE": { "path": "/assets/icons/crypto/CORE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "COREUSD": { "path": "/assets/icons/crypto/CORE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "COREUSDT": { "path": "/assets/icons/crypto/CORE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DYM": { "path": "/assets/icons/crypto/DYM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DYMUSD": { "path": "/assets/icons/crypto/DYM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DYMUSDT": { "path": "/assets/icons/crypto/DYM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MANTA": { "path": "/assets/icons/crypto/MANTA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MANTAUSD": { "path": "/assets/icons/crypto/MANTA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MANTAUSDT": { "path": "/assets/icons/crypto/MANTA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ETHFI": { "path": "/assets/icons/crypto/ETHFI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ETHFIUSD": { "path": "/assets/icons/crypto/ETHFI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ETHFIUSDT": { "path": "/assets/icons/crypto/ETHFI.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NOT": { "path": "/assets/icons/crypto/NOT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NOTUSD": { "path": "/assets/icons/crypto/NOT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NOTUSDT": { "path": "/assets/icons/crypto/NOT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PORTAL": { "path": "/assets/icons/crypto/PORTAL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PORTALUSD": { "path": "/assets/icons/crypto/PORTAL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PORTALUSDT": { "path": "/assets/icons/crypto/PORTAL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ONDO": { "path": "/assets/icons/crypto/ONDO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ONDOUSD": { "path": "/assets/icons/crypto/ONDO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ONDOUSDT": { "path": "/assets/icons/crypto/ONDO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BLAST": { "path": "/assets/icons/crypto/BLAST.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BLASTUSD": { "path": "/assets/icons/crypto/BLAST.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BLASTUSDT": { "path": "/assets/icons/crypto/BLAST.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AXL": { "path": "/assets/icons/crypto/AXL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AXLUSD": { "path": "/assets/icons/crypto/AXL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AXLUSDT": { "path": "/assets/icons/crypto/AXL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PRIME": { "path": "/assets/icons/crypto/PRIME.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PRIMEUSD": { "path": "/assets/icons/crypto/PRIME.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PRIMEUSDT": { "path": "/assets/icons/crypto/PRIME.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "C98": { "path": "/assets/icons/crypto/C98.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "C98USD": { "path": "/assets/icons/crypto/C98.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "C98USDT": { "path": "/assets/icons/crypto/C98.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "POLS": { "path": "/assets/icons/crypto/POLS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "POLSUSD": { "path": "/assets/icons/crypto/POLS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "POLSUSDT": { "path": "/assets/icons/crypto/POLS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SUPER": { "path": "/assets/icons/crypto/SUPER.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SUPERUSD": { "path": "/assets/icons/crypto/SUPER.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SUPERUSDT": { "path": "/assets/icons/crypto/SUPER.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "HIGH": { "path": "/assets/icons/crypto/HIGH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "HIGHUSD": { "path": "/assets/icons/crypto/HIGH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "HIGHUSDT": { "path": "/assets/icons/crypto/HIGH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ACH": { "path": "/assets/icons/crypto/ACH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ACHUSD": { "path": "/assets/icons/crypto/ACH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ACHUSDT": { "path": "/assets/icons/crypto/ACH.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PEOPLE": { "path": "/assets/icons/crypto/PEOPLE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PEOPLEUSD": { "path": "/assets/icons/crypto/PEOPLE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PEOPLEUSDT": { "path": "/assets/icons/crypto/PEOPLE.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BONK": { "path": "/assets/icons/crypto/BONK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BONKUSD": { "path": "/assets/icons/crypto/BONK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BONKUSDT": { "path": "/assets/icons/crypto/BONK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AERO": { "path": "/assets/icons/crypto/AERO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AEROUSD": { "path": "/assets/icons/crypto/AERO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AEROUSDT": { "path": "/assets/icons/crypto/AERO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ARKM": { "path": "/assets/icons/crypto/ARKM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ARKMUSD": { "path": "/assets/icons/crypto/ARKM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ARKMUSDT": { "path": "/assets/icons/crypto/ARKM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MEW": { "path": "/assets/icons/crypto/MEW.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MEWUSD": { "path": "/assets/icons/crypto/MEW.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "MEWUSDT": { "path": "/assets/icons/crypto/MEW.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CAT": { "path": "/assets/icons/crypto/CAT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CATUSD": { "path": "/assets/icons/crypto/CAT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CATUSDT": { "path": "/assets/icons/crypto/CAT.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DOGS": { "path": "/assets/icons/crypto/DOGS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DOGSUSD": { "path": "/assets/icons/crypto/DOGS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "DOGSUSDT": { "path": "/assets/icons/crypto/DOGS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NTRN": { "path": "/assets/icons/crypto/NTRN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NTRNUSD": { "path": "/assets/icons/crypto/NTRN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NTRNUSDT": { "path": "/assets/icons/crypto/NTRN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SUIA": { "path": "/assets/icons/crypto/SUIA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SUIAUSD": { "path": "/assets/icons/crypto/SUIA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "SUIAUSDT": { "path": "/assets/icons/crypto/SUIA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "VELO": { "path": "/assets/icons/crypto/VELO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "VELOUSD": { "path": "/assets/icons/crypto/VELO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "VELOUSDT": { "path": "/assets/icons/crypto/VELO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NKN": { "path": "/assets/icons/crypto/NKN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NKNUSD": { "path": "/assets/icons/crypto/NKN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NKNUSDT": { "path": "/assets/icons/crypto/NKN.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "XVG": { "path": "/assets/icons/crypto/XVG.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "XVGUSD": { "path": "/assets/icons/crypto/XVG.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "XVGUSDT": { "path": "/assets/icons/crypto/XVG.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PHA": { "path": "/assets/icons/crypto/PHA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PHAUSD": { "path": "/assets/icons/crypto/PHA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "PHAUSDT": { "path": "/assets/icons/crypto/PHA.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NYM": { "path": "/assets/icons/crypto/NYM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NYMUSD": { "path": "/assets/icons/crypto/NYM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NYMUSDT": { "path": "/assets/icons/crypto/NYM.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AIOZ": { "path": "/assets/icons/crypto/AIOZ.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AIOZUSD": { "path": "/assets/icons/crypto/AIOZ.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "AIOZUSDT": { "path": "/assets/icons/crypto/AIOZ.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NULS": { "path": "/assets/icons/crypto/NULS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NULSUSD": { "path": "/assets/icons/crypto/NULS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "NULSUSDT": { "path": "/assets/icons/crypto/NULS.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TEL": { "path": "/assets/icons/crypto/TEL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TELUSD": { "path": "/assets/icons/crypto/TEL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "TELUSDT": { "path": "/assets/icons/crypto/TEL.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BICO": { "path": "/assets/icons/crypto/BICO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BICOUSD": { "path": "/assets/icons/crypto/BICO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "BICOUSDT": { "path": "/assets/icons/crypto/BICO.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ARK": { "path": "/assets/icons/crypto/ARK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ARKUSD": { "path": "/assets/icons/crypto/ARK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "ARKUSDT": { "path": "/assets/icons/crypto/ARK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CEEK": { "path": "/assets/icons/crypto/CEEK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CEEKUSD": { "path": "/assets/icons/crypto/CEEK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },
  "CEEKUSDT": { "path": "/assets/icons/crypto/CEEK.svg", "color": "#9CA3AF", "type": "crypto", "isCrypto": true, "isIndex": false },

  // --- Extra Tokens ---
  "W":     { "path": "/assets/icons/extra/W.svg",       "color":"#A5F3EB","type":"token","isExtra":true },
  "T":     { "path": "/assets/icons/extra/T.svg",       "color":"#111111","type":"token","isExtra":true },
  "PILL":  { "path": "/assets/icons/extra/pill.svg",    "color":"#8EE9D5","type":"token","isExtra":true },
  "WHEEL": { "path": "/assets/icons/extra/wheel.svg",   "color":"#202020","type":"token","isExtra":true },
  "XDEX":  { "path": "/assets/icons/extra/xdex.svg",    "color":"#4A90E2","type":"token","isExtra":true },
  "RCR":   { "path": "/assets/icons/extra/recycle.svg", "color":"#1E90FF","type":"token","isExtra":true },
};

// Runtime injections (patch will fill overrides at load)
(logoMap as any).__COMMODITY_OVERRIDES__ = (logoMap as any).__COMMODITY_OVERRIDES__ || {};